name: sos_identity
description: A personal safety and identity emergency app.

publish_to: 'none'

version: 1.0.0+8   # ⬅️ Build number bumped from +1 to +2

environment:
  sdk: ^3.10.3


dependencies:
  dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1   # ✅ ADDED (correct place)

flutter:
  uses-material-design: true

# ✅ MUST be at TOP LEVEL (not inside flutter:)
flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true
